### ISSUE TITLE
Error while drawling square

### ISSUE THREAD

**Issue by austin-owensby** [SebLague/Chess-Challenge#172]
Version: 1.11
IDE: Visual Studio 2022 v17.6.5
Platform: Windows 10

I forked the repo on v1.11 and tried to simulate MyBot vs. EvilBot without changing anything just to see what the baseline statistics would come out as, and while running I got this exception in BoardUI.cs's DrawSquare function on line 305:
```
System.InvalidOperationException
  HResult=0x80131509
  Message=Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowInvalidOperationException_ConcurrentOperationsNotSupported()
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at ChessChallenge.Application.BoardUI.DrawSquare(Int32 file, Int32 rank) in C:\Users\aowen\Source\Repos\austin-owensby\Chess-Challenge\Chess-Challenge\src\Framework\Application\UI\BoardUI.cs:line 305
   at ChessChallenge.Application.BoardUI.Draw() in C:\Users\aowen\Source\Repos\austin-owensby\Chess-Challenge\Chess-Challenge\src\Framework\Application\UI\BoardUI.cs:line 203
   at ChessChallenge.Application.ChallengeController.Draw() in C:\Users\aowen\Source\Repos\austin-owensby\Chess-Challenge\Chess-Challenge\src\Framework\Application\Core\ChallengeController.cs:line 380
   at ChessChallenge.Application.Program.Main() in C:\Users\aowen\Source\Repos\austin-owensby\Chess-Challenge\Chess-Challenge\src\Framework\Application\Core\Program.cs:line 41
```

![ChessBug](https://github.com/SebLague/Chess-Challenge/assets/37364234/360b881a-6601-4ce3-99dd-5eaf158c7757)

Trying to include as much debug info as possible since it looks like there may not be a reliable way to reproduce this since from some quick research it may be based on different threads modifying the same collection at once.
![Locals1](https://github.com/SebLague/Chess-Challenge/assets/37364234/bc0f4030-c61c-45ab-8ae4-2a592c2c972e)
![Locals2](https://github.com/SebLague/Chess-Challenge/assets/37364234/f9545d16-7ffe-46a5-b137-320ac91d1f29)
![Locals3](https://github.com/SebLague/Chess-Challenge/assets/37364234/3ca68292-dbef-4765-8048-3ed7e958ccc2)
![Locals4](https://github.com/SebLague/Chess-Challenge/assets/37364234/36ff1651-3c7c-4315-9524-9c3ad89a968d)

![Threads](https://github.com/SebLague/Chess-Challenge/assets/37364234/4a2951f7-de86-4943-be6d-0e10cd9c875e)

**Comment by harrisi** [comment]
I opened a PR (#175), but I'm not sure if it's the correct way to do it. If you're able to reproduce this, maybe try that patch to see if it works? I can't recreate this locally.

**Comment by Earthcomputer** [comment]
I just got this error too while running 1000 games of My against EvilBot:
![image](https://github.com/SebLague/Chess-Challenge/assets/13084089/11b4ab1d-fa00-418f-adb1-7711564efccc)

**Comment by Xenymor** [comment]
I got it two times. It seems to happen on starting a new game
