### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by mcthouacbb** [SebLague/Chess-Challenge#285]
I got this error while playing MyBot vs EvilBot(EvilBot was modified to an old version of MyBot).
Not sure why this error is happening, but I figured I could at least post it for others to solve.

An error occurred while bot was thinking.
System.NullReferenceException: Object reference not set to an instance of an object.
   at ChessChallenge.Chess.Board.MovePiece(Int32 piece, Int32 startSquare, Int32 targetSquare) in C:\Dev\SeblagueChallenge\Chess-Challenge\src\Framework\Chess\Board\Board.cs:line 114
   at ChessChallenge.Chess.Board.MakeMove(Move move, Boolean inSearch) in C:\Dev\SeblagueChallenge\Chess-Challenge\src\Framework\Chess\Board\Board.cs:line 125
   at ChessChallenge.API.Board.MakeMove(Move move) in C:\Dev\SeblagueChallenge\Chess-Challenge\src\API\Board.cs:line 63
   at MyBot.Search(Int32 depth, Int32 alpha, Int32 beta, Boolean doNull) in C:\Dev\SeblagueChallenge\Chess-Challenge\src\My Bot\MyBot.cs:line 311
   at MyBot.Search(Int32 depth, Int32 alpha, Int32 beta, Boolean doNull) in C:\Dev\SeblagueChallenge\Chess-Challenge\src\My Bot\MyBot.cs:line 262
   at MyBot.Search(Int32 depth, Int32 alpha, Int32 beta, Boolean doNull) in C:\Dev\SeblagueChallenge\Chess-Challenge\src\My Bot\MyBot.cs:line 291
   at MyBot.Search(Int32 depth, Int32 alpha, Int32 beta, Boolean doNull) in C:\Dev\SeblagueChallenge\Chess-Challenge\src\My Bot\MyBot.cs:line 262
   at MyBot.Think(Board board, Timer timer) in C:\Dev\SeblagueChallenge\Chess-Challenge\src\My Bot\MyBot.cs:line 208
   at ChessChallenge.Application.ChallengeController.GetBotMove() in C:\Dev\SeblagueChallenge\Chess-Challenge\src\Framework\Application\Core\ChallengeController.cs:line 145
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at ChessChallenge.Application.ChallengeController.Update() in C:\Dev\SeblagueChallenge\Chess-Challenge\src\Framework\Application\Core\ChallengeController.cs:line 375
   at ChessChallenge.Application.Program.Main() in C:\Dev\SeblagueChallenge\Chess-Challenge\src\Framework\Application\Core\Program.cs:line 40

**Comment by R0b3rt1337** [comment]
Is your bot trying to make a null move? if so, you should use `TrySkipTurn` instead of `MakeMove(null)`.

**Comment by mcthouacbb** [comment]
@R0b3rt1337 I'm using TrySkipTurn for null moves. I'm pretty sure the error is something internal to the application, though I don't know what

**Comment by R0b3rt1337** [comment]
> @R0b3rt1337 I'm using TrySkipTurn for null moves. I'm pretty sure the error is something internal to the application, though I don't know what

I doubt its something internal, since the stacktrace leads to your `MyBot.cs:line 311` calling `Board#MakeMove`. Try printing the move before you make it, and also check if you are actually undoing your skip turns.

**Comment by mcthouacbb** [comment]
I haven't gotten any error since, and I've made a lot of changes, so there's no way for me to debug it. I'm gonna close this issue, since I doubt anyone will be able to figure out what's wrong.
