### ISSUE TITLE
GetOpponentPlayer() method  is not implemented

### ISSUE THREAD

**Issue by kabrownie** [SebLague/Chess-Challenge#306]
I am trying To prevent the bot from making a capture that would lead to a disadvantaged exchange, such as using a high-value piece like a queen to capture a lower-value piece like a pawn that is defended by a higher-value piece like a bishop.
I am using the **GetOpponentPlayer()** method to do this but am getting the error below at runtime. maybe am using the wrong method, if anyone knows how to implement this I will be glad

_An error occurred while bot was thinking.
System.NotImplementedException: The method or operation is not implemented.
   at ChessChallenge.API.Board.GetOpponentPlayer() in /home/kabrownie/projects/Chess-Challenge/Chess-Challenge/src/API/Board.cs:line 342
   at ChessChallenge.Application.MyBot.Think(Board board, Timer timer) in /home/kabrownie/projects/Chess-Challenge/Chess-Challenge/src/My Bot/MyBot.cs:line 50
   at ChessChallenge.Application.ChallengeController.GetBotMove() in /home/kabrownie/projects/Chess-Challenge/Chess-Challenge/src/Framework/Application/Core/ChallengeController.cs:line 151
Illegal move: Null in position: rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 1_

**Comment by dudecon** [comment]
Where did you find the "GetOpponentPlayer" function? I don't see it in any of the docs, or the source code.
The way I do this is using the boolean `board.SquareIsAttackedByOpponent(targetSquare)` to see if the location I am thinking of capturing is defended by the opponent. If it is, you can compare the value of the pieces to see if it is a favorable trade.

**Comment by kabrownie** [comment]
thanks
