### ISSUE TITLE
Error from the base project

### ISSUE THREAD

**Issue by 101dal** [SebLague/Chess-Challenge#332]
When my code executed, I suddenly got this error 
```
Exception has occurred: CLR/System.NullReferenceException
An unhandled exception of type 'System.NullReferenceException' occurred in Chess-Challenge.dll: 'Object reference not set to an instance of an object.'
   at ChessChallenge.Chess.Board.MovePiece(Int32 piece, Int32 startSquare, Int32 targetSquare) in C:\Users\augus\Desktop\CODE\Chess-Challenge-main\Chess-Challenge\src\Framework\Chess\Board\Board.cs:line 114
   at ChessChallenge.Chess.Board.MakeMove(Move move, Boolean inSearch) in C:\Users\augus\Desktop\CODE\Chess-Challenge-main\Chess-Challenge\src\Framework\Chess\Board\Board.cs:line 143
   at ChessChallenge.Application.ChallengeController.PlayMove(Move move) in C:\Users\augus\Desktop\CODE\Chess-Challenge-main\Chess-Challenge\src\Framework\Application\Core\ChallengeController.cs:line 256
   at ChessChallenge.Application.ChallengeController.Update() in C:\Users\augus\Desktop\CODE\Chess-Challenge-main\Chess-Challenge\src\Framework\Application\Core\ChallengeController.cs:line 366
   at ChessChallenge.Application.Program.Main() in C:\Users\augus\Desktop\CODE\Chess-Challenge-main\Chess-Challenge\src\Framework\Application\Core\Program.cs:line 40
```

**Comment by carsonetb** [comment]
Does this also happen when you run with 'dotnet run' command? I'm assuming it could be a little bit different, or possibly give more context on the error. Is it a fen string that's been loaded incorrectly, or is this happening after you or your bot makes a move? It would be nice to have some more context if possible. 

This was opened three days ago, so you might've already fixed the problem.
