### ISSUE TITLE
`System.AccessViolationException`: Attempted to read or write protected memory

### ISSUE THREAD

**Issue by eduherminio** [SebLague/Chess-Challenge#348]
When running it in a Windows 11 and VM I get the following error.

```bash
Launching Chess-Challenge version 1.15
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at Raylib_cs.Raylib.LoadTextureFromImage(Raylib_cs.Image)
--------------------------------
   at ChessChallenge.Application.UIHelper..cctor()
   at ChessChallenge.Application.UIHelper.GetResourcePath(System.String[])
   at ChessChallenge.Application.BoardUI.LoadPieceTexture()
   at ChessChallenge.Application.BoardUI..ctor()
   at ChessChallenge.Application.ChallengeController..ctor()
   at ChessChallenge.Application.Program.Main()
```

Sounds related to https://github.com/ChrisDill/Raylib-cs/issues/172, but I don't know why I'm getting it in that VM and not anywhere else. Locally it works fine with my Windows 10.

**Comment by ChickenThief** [comment]
I got the same issue on windows 10, with a new copy of windows, and a fresh visual studio install. I didn't get that error this morning on a different machine that also had a new copy of windows and a fresh visual studio install. I'll keep you updated if I find anything out.

**Comment by eduherminio** [comment]
Let me move the issue to Raylib repo directly, @SebLague looks busy and it's probably going to end up there anyway.
