### ISSUE TITLE
System.InvalidOperationException while testing my bot

### ISSUE THREAD

**Issue by TheBestMinecraftPlayerFromWorld** [SebLague/Chess-Challenge#377]
While testing my bot for the 1000 games I got following error.

```
Unhandled exception. System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at ChessChallenge.Application.BoardUI.DrawSquare(Int32 file, Int32 rank) in c:\Users\TBMPFW\Chess-Challenge\Chess-Challenge\src\Framework\Application\UI\BoardUI.cs:line 327
   at ChessChallenge.Application.BoardUI.ForEachSquare(Action`2 action) in c:\Users\TBMPFW\Chess-Challenge\Chess-Challenge\src\Framework\Application\UI\BoardUI.cs:line 233
   at ChessChallenge.Application.BoardUI.Draw() in c:\Users\TBMPFW\Chess-Challenge\Chess-Challenge\src\Framework\Application\UI\BoardUI.cs:line 205
   at ChessChallenge.Application.ChallengeController.Draw() in c:\Users\TBMPFW\Chess-Challenge\Chess-Challenge\src\Framework\Application\Core\ChallengeController.cs:line 382
   at ChessChallenge.Application.Program.Main() in c:\Users\TBMPFW\Chess-Challenge\Chess-Challenge\src\Framework\Application\Core\Program.cs:line 41
```

Thanks,
TBMPFW

**Comment by TheBestMinecraftPlayerFromWorld** [comment]
It only happend once. So if anyone's wondering why they've got this error, just restart the bot.
