### ISSUE TITLE
System.NullReferenceException: 'Object reference not set to an instance of an object.'  PieceLists is missing some entries

### ISSUE THREAD

**Issue by EikeSchwass** [SebLague/Chess-Challenge#42]
Hi, just got System.NullReferenceException: 'Object reference not set to an instance of an object.' Looks like it rarely happens, but just in case I documented the stack trace here:
`System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Chess-Challenge
  StackTrace:
   at ChessChallenge.Chess.Board.MovePiece(Int32 piece, Int32 startSquare, Int32 targetSquare) in C:\Users\e.schwass\Source\Repos\Chess-Challenge\Chess-Challenge\src\Framework\Chess\Board\Board.cs:line 114
   at ChessChallenge.Chess.Board.MakeMove(Move move, Boolean inSearch) in C:\Users\e.schwass\Source\Repos\Chess-Challenge\Chess-Challenge\src\Framework\Chess\Board\Board.cs:line 143
   at ChessChallenge.Application.ChallengeController.PlayMove(Move move) in C:\Users\e.schwass\Source\Repos\Chess-Challenge\Chess-Challenge\src\Framework\Application\Core\ChallengeController.cs:line 256
   at ChessChallenge.Application.ChallengeController.Update() in C:\Users\e.schwass\Source\Repos\Chess-Challenge\Chess-Challenge\src\Framework\Application\Core\ChallengeController.cs:line 366
   at ChessChallenge.Application.Program.Main() in C:\Users\e.schwass\Source\Repos\Chess-Challenge\Chess-Challenge\src\Framework\Application\Core\Program.cs:line 40
`

![image](https://github.com/SebLague/Chess-Challenge/assets/11982172/d9f69530-f176-4e7f-a734-c30adcd3af62)

**Comment by Binto86** [comment]
Got the exact same thing

**Comment by Binto86** [comment]
For me this was a dumb error, I was trying to make move I already made

**Comment by Chrislee187** [comment]
This may be the same issue as #46
