### ISSUE TITLE
Error building the project

### ISSUE THREAD

**Issue by kevipegoraro** [SebLague/Chess-Challenge#420]
When i run Chess-Challenge.csproj, I get it:

[Running] dotnet run --project "e:\Chess-Challenge-main\Chess-Challenge-main\Chess-Challenge\Chess-Challenge.csproj"
Launching Chess-Challenge version 1.18
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path 'e:\Chess-Challenge-main\Chess-Challenge-main\src\My Bot\MyBot.cs'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path)
   at ChessChallenge.Application.ChallengeController.GetTokenCount() in e:\Chess-Challenge-main\Chess-Challenge-main\Chess-Challenge\src\Framework\Application\Core\ChallengeController.cs:line 221
   at ChessChallenge.Application.ChallengeController..ctor() in e:\Chess-Challenge-main\Chess-Challenge-main\Chess-Challenge\src\Framework\Application\Core\ChallengeController.cs:line 62
   at ChessChallenge.Application.Program.Main() in e:\Chess-Challenge-main\Chess-Challenge-main\Chess-Challenge\src\Framework\Application\Core\Program.cs:line 32

**Comment by kevipegoraro** [comment]
The solution was, i runned Chess-Challenge-main\ and not in the Chess-Challenge-main\Chess-Challenge
