### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by 101dal** [SebLague/Chess-Challenge#94]
When I try to move a piece I got this error:
```
Exception has occurred: CLR/System.NullReferenceException
An unhandled exception of type 'System.NullReferenceException' occurred in System.Private.CoreLib.dll: 'Object reference not set to an instance of an object.'
   at ChessChallenge.Chess.Board.MovePiece(Int32 piece, Int32 startSquare, Int32 targetSquare) in C:\Users\augus\Desktop\CODE\Chess-Challenge-main\Chess-Challenge\src\Framework\Chess\Board\Board.cs:line 114
   at ChessChallenge.Chess.Board.MakeMove(Move move, Boolean inSearch) in C:\Users\augus\Desktop\CODE\Chess-Challenge-main\Chess-Challenge\src\Framework\Chess\Board\Board.cs:line 143
   at ChessChallenge.API.Board.MakeMove(Move move) in C:\Users\augus\Desktop\CODE\Chess-Challenge-main\Chess-Challenge\src\API\Board.cs:line 72
   at MyBot.Minmax(Board board, Int32 depth, Boolean maximizingPlayer, Move move) in C:\Users\augus\Desktop\CODE\Chess-Challenge-main\Chess-Challenge\src\My Bot\MyBot.cs:line 34
   at MyBot.Minmax(Board board, Int32 depth, Boolean maximizingPlayer, Move move) in C:\Users\augus\Desktop\CODE\Chess-Challenge-main\Chess-Challenge\src\My Bot\MyBot.cs:line 46
   at MyBot.Think(Board board, Timer timer) in C:\Users\augus\Desktop\CODE\Chess-Challenge-main\Chess-Challenge\src\My Bot\MyBot.cs:line 19
   at ChessChallenge.Application.ChallengeController.GetBotMove() in C:\Users\augus\Desktop\CODE\Chess-Challenge-main\Chess-Challenge\src\Framework\Application\Core\ChallengeController.cs:line 147
--- End of stack trace from previous location ---
   at ChessChallenge.Application.ChallengeController.Update() in C:\Users\augus\Desktop\CODE\Chess-Challenge-main\Chess-Challenge\src\Framework\Application\Core\ChallengeController.cs:line 374
   at ChessChallenge.Application.Program.Main() in C:\Users\augus\Desktop\CODE\Chess-Challenge-main\Chess-Challenge\src\Framework\Application\Core\Program.cs:line 40
```

This is my current MyBot:
```cs
using ChessChallenge.API;
using System;

public class MyBot : IChessBot
{

    public Move Think(Board board, Timer timer)
    {
        Move[] allMoves = board.GetLegalMoves();

        // Pick a random move to play if nothing better is found
        Random rng = new();
        Move moveToPlay = allMoves[rng.Next(allMoves.Length)];

        int currentMinMax;

        // Perform Minimax based on the current player's turn
        if (board.IsWhiteToMove) {
            // Maximize for white player's turn
            currentMinMax = Minmax(board, 3, true, allMoves[0]);
        } else {
            // Minimize for black player's turn
            currentMinMax = Minmax(board, 3, false, allMoves[0]);
        }

        Console.WriteLine(currentMinMax.ToString());

        return moveToPlay;
    }

    private int Minmax(Board board, int depth, bool maximizingPlayer, Move move) {
        
        // Terminal condition: If depth is 0, checkmate or draw, return the evaluation
        if (depth == 0 || board.IsInCheckmate() || board.IsDraw()) {
            return staticEvaluation(board);
        }

        Move[] allMoves = board.GetLegalMoves(); 

        if (maximizingPlayer) {
            // Maximize the evaluation for the maximizing player (White)
            board.MakeMove(move);
            int maxEval = int.MinValue;
            foreach (Move newMove in allMoves) {
                int eval = Minmax(board, depth - 1, false, newMove);
                maxEval = Math.Max(eval, maxEval);
            }
            board.UndoMove(move);
            return maxEval;
        } else {
            // Minimize the evaluation for the minimizing player (Black)
            board.MakeMove(move);
            int minEval = int.MaxValue;
            foreach (Move newMove in allMoves) {
                int eval = Minmax(board, depth - 1, true, newMove);
                minEval = Math.Min(eval, minEval);
            }
            board.UndoMove(move);
            return minEval;
        }
    }

    private int staticEvaluation(Board board) {

        // Piece values: null, pawn, knight, bishop, rook, queen, king
        int[] pieceValues = { 0, 100, 300, 300, 500, 900, 10000 };

        // Define the base evaluation to 0
        int eval = 0;

        // Add +1 for each white piece and -1 for each black piece
        foreach (PieceList pieceList in board.GetAllPieceLists()) {
            foreach (Piece piece in pieceList){
                if (piece.IsWhite) {
                    eval += pieceValues[(int)piece.PieceType];
                } else {
                    eval -= pieceValues[(int)piece.PieceType];
                }
            }
        }
        
        return eval;
    }   
}

```

**Comment by alpheratz0** [comment]
You are calling GetLegalMoves before moving a piece, which in this case is not what you want.
Make the move and **then** call `GetLegalMoves`.

```cs
board.MakeMove(move);
Move[] allMoves = board.GetLegalMoves(); 
```

**Comment by 101dal** [comment]
Ok thank you
